### ISSUE TITLE
Как развернуть у себя

### ISSUE THREAD

**Issue by jeffscrum** [DagazProject/DagazBotV3#1]
Добрый день,
Прочел вашу статью на хабре. Подскажите, как я могу настроить и развернуть движок на собственном сервере, для того чтобы организовать свой небольшой квест для друзей?
Каким образом мне прописать токен бота, администратором назначить себя и тд?
Спасибо

**Comment by DagazProject** [comment]
Добрый день
 
*  У вас должен быть PostgreSQL и там надо создать пустую БД
*  Проект запускается под Node.js и его надо установить на сервер
*  Загружаем проект с GitHub-а и в Node.js из его каталога ‘ npm install ’ (ошибок быть не должно)
*  Здесь прописываем параметры подключения к PostgreSQL
*  При первом старте TypeORM создаст все таблицы ‘ npm start ’
*  Миграции почему-то не заработали, поэтому  это и  это придётся накатить на БД вручную
*  В  Telegram надо зарегистрировать бота и полученный токен прописать в таблице  service
​​​​​​​После этого можно запускаться, должно работать. Шаги 5-7 могу сделать за вас и прислать вам дамп БД, если сообщите токен вашего бота.
 
С Уважением,
  Валентин Челноков
  
>Воскресенье, 25 августа 2024, 20:14 +03:00 от Jeff Scrum ***@***.***>:
> 
> 
>Добрый день,
>Прочел вашу статью на хабре. Подскажите, как я могу настроить и развернуть движок на собственном сервере, для того чтобы организовать свой небольшой квест для друзей?
>Каким образом мне прописать токен бота, администратором назначить себя и тд?
>Спасибо
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you are subscribed to this thread. Message ID:  <DagazProject/DagazBotV3/issues/1 @ github . com> 
 
 
--
Валентин Челноков
Отправлено из Почты  Mail.ru

**Comment by jeffscrum** [comment]
Спасибо за ответ, думаю что я попробую вначале сам.
В вашем ответе "съелось" что нужно накатить вручную. 
У меня это выглядит вот так `Миграции почему-то не заработали, поэтому  это и  это придётся накатить на БД вручную`.
Напишите, пожалуйста, еще раз какие это файлы.

Upd:
Я сделал шаги до миграции, но что мигрировать не знаю. И не знаю формата в котором записать токен бота

Пожалуй, я воспользуюсь вашим предложением с пунктами 5-7. Токен бота вот такой (токен изменен)
`XXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

**Comment by DagazProject** [comment]
Ох, вы зря выложили сюда токен. Им может воспользоваться кто угодно и тогда вы не сможете им воспользоваться.
Накатить надо sql который внутри миграций: 
https://github.com/DagazProject/DagazBotV3/blob/master/src/migration/1710490418239-init.ts
https://github.com/DagazProject/DagazBotV3/blob/master/src/migration/1710502781744-sp.ts

**Comment by DagazProject** [comment]
А всё вижу, токен изменён. У меня Security Alert ругнулся

**Comment by DagazProject** [comment]
Настройки для подключения к БД здесь: https://github.com/DagazProject/DagazBotV3/blob/master/src/data-source.ts#L40-L45

**Comment by jeffscrum** [comment]
Токен был давно уже отозван, поэтому не боялся выложить его в публичный доступ.
Данные для подключения к БД я поменял, но вот как импортировать пока не разобрался. 
В nodejs я не понимаю ровным счетом ничего, а как sql оно не импортируется

**Comment by DagazProject** [comment]
Ну вот я тоже как не бился почему-то не смог заставить миграции работать. Поэтому заходим в psql и копипастим руками.
Я же говорю, я могу подготовить начальный дамп и переслать по почте, останется его накатить в БД. Токен сами забъёте.

**Comment by DagazProject** [comment]
Отправил дамп по почте.
